// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-YD23-5wnQuXtxlDQwhedgIBG55mbq58',
    appId: '1:978345093220:web:b72056a0bbc027aaca9771',
    messagingSenderId: '978345093220',
    projectId: 'safe-ride-b6af5',
    authDomain: 'safe-ride-b6af5.firebaseapp.com',
    storageBucket: 'safe-ride-b6af5.firebasestorage.app',
    measurementId: 'G-XZZT2JPZ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxwOy5Rn9giSlw3eoT8D7J2azHMFDj6EU',
    appId: '1:978345093220:android:ce1688afb5b6a8b8ca9771',
    messagingSenderId: '978345093220',
    projectId: 'safe-ride-b6af5',
    storageBucket: 'safe-ride-b6af5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtgOhX09BNSmuoa7R8GCrR_f8ghBcdW0',
    appId: '1:978345093220:ios:3968cde095cde9d1ca9771',
    messagingSenderId: '978345093220',
    projectId: 'safe-ride-b6af5',
    storageBucket: 'safe-ride-b6af5.firebasestorage.app',
    iosClientId: '978345093220-5nfsabi6mglp50rbt7oqqfgb6971q75o.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeRideApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtgOhX09BNSmuoa7R8GCrR_f8ghBcdW0',
    appId: '1:978345093220:ios:3968cde095cde9d1ca9771',
    messagingSenderId: '978345093220',
    projectId: 'safe-ride-b6af5',
    storageBucket: 'safe-ride-b6af5.firebasestorage.app',
    iosClientId: '978345093220-5nfsabi6mglp50rbt7oqqfgb6971q75o.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeRideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-YD23-5wnQuXtxlDQwhedgIBG55mbq58',
    appId: '1:978345093220:web:9617c2011a0075f5ca9771',
    messagingSenderId: '978345093220',
    projectId: 'safe-ride-b6af5',
    authDomain: 'safe-ride-b6af5.firebaseapp.com',
    storageBucket: 'safe-ride-b6af5.firebasestorage.app',
    measurementId: 'G-NR951REQB7',
  );
}
