// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQ8MMzTZwb3Uh3ch36sR_KiUjqiKbNC8',
    appId: '1:860734666404:web:67f60d9c87f2fad5639831',
    messagingSenderId: '860734666404',
    projectId: 'safe-ride-app-5733f',
    authDomain: 'safe-ride-app-5733f.firebaseapp.com',
    storageBucket: 'safe-ride-app-5733f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnp3j72ieq9aWEZCqj3KOONX9whWBKODI',
    appId: '1:860734666404:android:936a268bd90b7b51639831',
    messagingSenderId: '860734666404',
    projectId: 'safe-ride-app-5733f',
    storageBucket: 'safe-ride-app-5733f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKO4D1XpbFh5hSDTuxeEg3J4IcbWpodqw',
    appId: '1:860734666404:ios:28cbf0cb09ddd467639831',
    messagingSenderId: '860734666404',
    projectId: 'safe-ride-app-5733f',
    storageBucket: 'safe-ride-app-5733f.firebasestorage.app',
    iosBundleId: 'com.example.safeRideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKO4D1XpbFh5hSDTuxeEg3J4IcbWpodqw',
    appId: '1:860734666404:ios:28cbf0cb09ddd467639831',
    messagingSenderId: '860734666404',
    projectId: 'safe-ride-app-5733f',
    storageBucket: 'safe-ride-app-5733f.firebasestorage.app',
    iosBundleId: 'com.example.safeRideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQ8MMzTZwb3Uh3ch36sR_KiUjqiKbNC8',
    appId: '1:860734666404:web:26f94293b12b1ec3639831',
    messagingSenderId: '860734666404',
    projectId: 'safe-ride-app-5733f',
    authDomain: 'safe-ride-app-5733f.firebaseapp.com',
    storageBucket: 'safe-ride-app-5733f.firebasestorage.app',
  );
}
